server:
  port: 8081

spring:
  application:
    name: user-client
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      database: ${MONGO_DB}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: ${DB_HOST}
      port: 27017
      authentication-database: admin
  liquibase:
    change-log: classpath:db/db.changelog.yaml
    default-schema: ${MONGO_DB}
    url: jdbc:mongodb://${DB_HOST}:27017/${MONGO_DB}
    password: ${MONGO_USERNAME}
    user: ${MONGO_PASSWORD}
    driver-class-name: liquibase.ext.mongodb.database.MongoClientDriver
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

security:
  jwt:
    secret: c651749e8354adb09452a8ad14d4beadb7d57064d6cfb5c0e812bc30724458d187f43e58c22c30486303bbfc655391860952e92add87b5ce9e2ac7cdc612ad73=
    access: 30
    refresh: 336
    activation: 24
    reset: 24