server:
  port: 8081

spring:
  application:
    name: user-client
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}?currentSchema=${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db/db.changelog.yaml
    default-schema: ${POSTGRES_DB}
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}?currentSchema=${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    user: ${POSTGRES_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

security:
  jwt:
    secret: c651749e8354adb09452a8ad14d4beadb7d57064d6cfb5c0e812bc30724458d187f43e58c22c30486303bbfc655391860952e92add87b5ce9e2ac7cdc612ad73=
    access: 30
    refresh: 336
    activation: 24
    reset: 24