server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}?currentSchema=${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/db.changelog.yaml
    default-schema: ${DB_DATABASE}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka