server:
  port: 8081

spring:
  application:
    name: user-client
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      database: ${MONGO_DB}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: ${DB_HOST}
      port: 27017
      authentication-database: admin
  liquibase:
    change-log: classpath:db/db.changelog.yaml
    enabled: true
    url: jdbc:postgresql://${PG_HOST}:5432/${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    user: ${POSTGRES_USERNAME}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    listener:
      ack-mode: manual_immediate
    consumer:
      properties:
        group.id: 1
        bootstrap-servers: ${KAFKA_HOST}
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

security:
  jwt:
    secret: c651749e8354adb09452a8ad14d4beadb7d57064d6cfb5c0e812bc30724458d187f43e58c22c30486303bbfc655391860952e92add87b5ce9e2ac7cdc612ad73=
    access: 30
    refresh: 336
    activation: 24
    reset: 24