CREATE TABLE IF NOT EXISTS users
(
    id           bigint generated by default as identity (START WITH 5),
    name         varchar(255)        NOT NULL,
    surname      varchar(255)        NOT NULL,
    email        varchar(255) UNIQUE NOT NULL unique,
    password     varchar(255)        NOT NULL,
    role         varchar(255)        NOT NULL,
    is_activated boolean             NOT NULL DEFAULT false,
    constraint "user_pkey" PRIMARY KEY ("id")
);