--liquibase formatted sql
--changeset lisov:1

CREATE TABLE IF NOT EXISTS events
(
    dtype        varchar(255) NOT NULL,
    id           bigint generated by default as identity,
    aggregate_id varchar(255),
    type         varchar(255) NOT NULL,
    timestamp    timestamp    NOT NULL,
    payload      jsonb
);