create table users
(
    id           bigint generated by default as identity,
    first_name   varchar(255) not null,
    last_name    varchar(255),
    email        varchar(255) not null unique,
    password     varchar(255),
    phone_number varchar(255),
    role         varchar(255) not null,
    created_at   timestamp without time zone,
    updated_at   timestamp without time zone,
    primary key (id)
);