apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-client-mongo
spec:
  serviceName: user-client-mongo
  replicas: 1
  selector:
    matchLabels:
      app: user-client-mongo
  template:
    metadata:
      labels:
        app: user-client-mongo
    spec:
      containers:
        - name: user-client-db
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGO_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGO_PASSWORD
            - name: MONGO_DB
              value: users
      volumes:
        - name: db-user-client-data
          hostPath:
            path: /data-user-client
  volumeClaimTemplates:
    - metadata:
        name: db-user-client-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi