apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 4
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
        - name: redis-init
          image: redis:latest
          command:
            - bash
            - "-c"
            - |
              set -ex
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              if [[ $ordinal -eq 0 ]]; then
                cp /mnt/master.conf /etc/redis-config.conf
              else
                cp /mnt/slave.conf /etc/redis-config.conf
              fi
          volumeMounts:
            - name: redis-claim
              mountPath: /etc
            - name: config-map
              mountPath: /mnt/
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - "/etc/redis-config.conf"
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-claim
              mountPath: /etc
      volumes:
        - name: config-map
          configMap:
            name: redis-configmap
  volumeClaimTemplates:
    - metadata:
        name: redis-claim
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi