apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-requests-from-qaprotours
spec:
  selector:
    matchLabels:
      app: user-client
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/default/sa/qaprotours-serviceaccount"