apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-client
  template:
    metadata:
      labels:
        app: user-client
    spec:
      containers:
        - name: user-client-app
          image: ilyalisov/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: PG_HOST
              value: postgres-kafka
            - name: POSTGRES_DB
              value: event_store
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-kafka
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-kafka
                  key: POSTGRES_PASSWORD
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGO_PASSWORD
            - name: DB_HOST
              value: user-client-mongo
            - name: MONGO_DB
              value: users
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-client-configmap
                  key: KAFKA_HOST
            - name: REDIS_HOST
              value: redis
          volumeMounts:
            - name: my-service-account-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      volumes:
        - name: my-service-account-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600